# Generated by Django 5.0.3 on 2024-03-16 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_post', '0002_alter_post_options_post_publish_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('PF', 'Published'), ('DF', 'Draft')], default='PF', max_length=2),
        ),
    ]
