# Generated by Django 4.2.10 on 2024-02-28 16:35

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core_user", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="created_at",
            new_name="created",
        ),
        migrations.RenameField(
            model_name="user",
            old_name="updated_at",
            new_name="updated",
        ),
    ]
