# Generated by Django 4.2.10 on 2024-02-28 20:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core_post", "0001_initial"),
        ("core_user", "0002_rename_created_at_user_created_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="posts_liked",
            field=models.ManyToManyField(related_name="liked_by", to="core_post.post"),
        ),
    ]
